/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    dealers: Dealer;
    'service-providers': ServiceProvider;
    listings: Listing;
    articles: Article;
    guides: Guide;
    reviews: Review;
    reports: Report;
    'contact-messages': ContactMessage;
    'saved-searches': SavedSearch;
    notifications: Notification;
    'audit-logs': AuditLog;
    'verification-documents': VerificationDocument;
    conversations: Conversation;
    messages: Message;
    'whatsapp-submissions': WhatsappSubmission;
    'whatsapp-messages': WhatsappMessage;
    'whatsapp-media': WhatsappMedia;
    'featured-orders': FeaturedOrder;
    inquiries: Inquiry;
    media: Media;
    inspections: Inspection;
    'phone-otps': PhoneOtp;
    'crsp-schedule': CrspSchedule;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    'service-providers': ServiceProvidersSelect<false> | ServiceProvidersSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'saved-searches': SavedSearchesSelect<false> | SavedSearchesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'verification-documents': VerificationDocumentsSelect<false> | VerificationDocumentsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'whatsapp-submissions': WhatsappSubmissionsSelect<false> | WhatsappSubmissionsSelect<true>;
    'whatsapp-messages': WhatsappMessagesSelect<false> | WhatsappMessagesSelect<true>;
    'whatsapp-media': WhatsappMediaSelect<false> | WhatsappMediaSelect<true>;
    'featured-orders': FeaturedOrdersSelect<false> | FeaturedOrdersSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inspections: InspectionsSelect<false> | InspectionsSelect<true>;
    'phone-otps': PhoneOtpsSelect<false> | PhoneOtpsSelect<true>;
    'crsp-schedule': CrspScheduleSelect<false> | CrspScheduleSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Automatic public profile URL: /sellers/[publicSlug].
   */
  publicSlug?: string | null;
  /**
   * Optional public seller introduction.
   */
  bio?: string | null;
  /**
   * Public website, including https://.
   */
  website?: string | null;
  /**
   * Public county for buyers looking nearby.
   */
  county?: string | null;
  town?: string | null;
  accountStatus?: ('active' | 'warned' | 'suspended' | 'banned') | null;
  suspensionEndsAt?: string | null;
  moderationNote?: string | null;
  verificationExpiresAt?: string | null;
  /**
   * MSISDN in 2547XXXXXXXX format — used for M-Pesa STK push, WhatsApp contact, and phone-OTP login (find-or-create in api/auth/otp/verify relies on this being unique).
   */
  phone: string;
  whatsappOptIn?: boolean | null;
  role: 'buyer' | 'individual_seller' | 'dealer' | 'moderator' | 'admin';
  /**
   * Signup intent. An admin must approve any role change.
   */
  requestedRole?: ('buyer' | 'individual_seller' | 'dealer') | null;
  avatar?: (number | null) | Media;
  /**
   * National ID / passport checked by a moderator. Drives the "Verified ID" badge on the buyer-facing profile, same pattern Jiji and PigiaMe use.
   */
  idVerified?: boolean | null;
  savedListings?: (number | Listing)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  /**
   * e.g. "2019 Toyota Harrier — Foreign Used, 1998cc" or "Massey Ferguson MF-385 Tractor". Shown in search results and the browser tab.
   */
  title: string;
  slug: string;
  seller: number | User;
  /**
   * Set automatically if the seller has a dealer profile. Powers the dealer storefront grouping.
   */
  dealer?: (number | null) | Dealer;
  category:
    | 'car'
    | 'motorcycle'
    | 'tractor'
    | 'heavy-machinery'
    | 'pickup-van'
    | 'truck'
    | 'bus'
    | 'trailer'
    | 'tuk-tuk'
    | 'spare-parts';
  condition: 'brand-new' | 'locally-assembled' | 'foreign-used' | 'locally-used';
  make: string;
  model: string;
  /**
   * Generated canonical taxonomy key for SEO landing pages.
   */
  makeSlug?: string | null;
  /**
   * Generated canonical taxonomy key for SEO landing pages.
   */
  modelSlug?: string | null;
  /**
   * Manufacturer or CRSP model number.
   */
  modelNumber?: string | null;
  trim?: string | null;
  yearOfManufacture: number;
  transmission?: ('manual' | 'automatic' | 'cvt') | null;
  driveConfiguration?: ('2wd' | '4wd' | 'awd' | 'fwd' | 'rwd') | null;
  fuelType?: ('petrol' | 'diesel' | 'hybrid' | 'electric') | null;
  /**
   * Engine capacity in cc (or horsepower/KW equivalent). Feeds the import duty calculator.
   */
  engineCc?: number | null;
  mileageKm?: number | null;
  bodyType?: ('sedan' | 'suv' | 'hatchback' | 'wagon' | 'pickup' | 'van' | 'coupe' | 'convertible') | null;
  /**
   * Gross vehicle weight (GVW) in kilograms.
   */
  grossVehicleWeightKg?: number | null;
  seatingCapacity?: number | null;
  color?: string | null;
  /**
   * Optional matching KRA CRSP record.
   */
  crspRecord?: (number | null) | CrspSchedule;
  /**
   * CRSP value in KES at the time this listing was created or updated.
   */
  crspValueKes?: number | null;
  heavyMachineSpecs?: {
    equipmentType?:
      | (
          | 'excavator'
          | 'bulldozer'
          | 'wheel-loader'
          | 'grader'
          | 'backhoe-loader'
          | 'tractor'
          | 'crane'
          | 'forklift'
          | 'compactor-/-roller'
          | 'combine-harvester'
          | 'cane-loader'
          | 'generator'
          | 'other'
        )
      | null;
    /**
     * Power output in Horsepower (HP) or CC / KW (from KRA schedule).
     */
    powerRatingHp?: number | null;
    operatingHours?: number | null;
    /**
     * e.g. "3.5 tonne", "20-tonne excavator", "100 KVA", "2.5m³ bucket"
     */
    capacityOrTonnage?: string | null;
    /**
     * Comma-separated, e.g. "bucket, breaker, forks, canopy"
     */
    attachments?: string | null;
  };
  sparePartDetails?: {
    /**
     * e.g. "Alternator", "Headlight assembly", "ECU"
     */
    partType?: string | null;
    /**
     * Comma-separated, e.g. "Toyota Harrier 2015-2020, Toyota Vanguard"
     */
    compatibleModels?: string | null;
    partCondition?: ('new' | 'refurbished' | 'used') | null;
  };
  /**
   * Only relevant for foreign-used imports.
   */
  dutyStatus?: ('duty-paid' | 'bonded-pre-clearance') | null;
  /**
   * Not shown publicly; used for internal duplicate/fraud detection.
   */
  vinOrChassis?: string | null;
  price: number;
  negotiable?: boolean | null;
  currency?: 'KES' | null;
  description: string;
  /**
   * Optional editor overrides. Leave empty to use the accurate title, description, and public listing URL generated by the marketplace.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    indexing?: ('auto' | 'index' | 'noindex') | null;
  };
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  /**
   * Optional YouTube/TikTok walkaround link.
   */
  videoUrl?: string | null;
  county:
    | 'Nairobi'
    | 'Mombasa'
    | 'Kiambu'
    | 'Nakuru'
    | 'Uasin Gishu'
    | 'Kisumu'
    | 'Machakos'
    | 'Kajiado'
    | 'Kilifi'
    | 'Meru'
    | 'Nyeri'
    | 'Other';
  town?: string | null;
  /**
   * Optional approximate pin for nearby search. Do not require an individual seller’s exact home location.
   */
  latitude?: number | null;
  longitude?: number | null;
  status?: ('draft' | 'pending-review' | 'active' | 'sold' | 'expired' | 'rejected') | null;
  /**
   * Auto-set by the price-outlier check on create/update. A flagged listing still goes live but is queued for a human look — this is a nudge, not a block.
   */
  moderationFlag?: ('none' | 'price-outlier-low' | 'duplicate-vin') | null;
  riskScore?: number | null;
  riskReasons?:
    | {
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  moderationNote?: string | null;
  /**
   * Set by a paid FeaturedOrder, not directly by the seller.
   */
  featured?: boolean | null;
  featuredUntil?: string | null;
  views?: number | null;
  inquiryCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: number;
  owner: number | User;
  businessName: string;
  /**
   * Used in /dealers/[slug]. Lowercase, hyphenated.
   */
  slug: string;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  description?: string | null;
  /**
   * Optional editor overrides for this public storefront. Leave empty to use generated page metadata.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    indexing?: ('auto' | 'index' | 'noindex') | null;
  };
  county: 'Nairobi' | 'Mombasa' | 'Kiambu' | 'Nakuru' | 'Uasin Gishu' | 'Kisumu' | 'Machakos' | 'Other';
  town?: string | null;
  physicalAddress?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  verificationExpiresAt?: string | null;
  verificationNote?: string | null;
  contactPhone: string;
  whatsappNumber?: string | null;
  dealsIn?: ('new' | 'import' | 'locally-used' | 'heavy-machinery')[] | null;
  verificationStatus?: ('unverified' | 'pending' | 'verified' | 'rejected') | null;
  /**
   * Business permit, KRA PIN certificate, ID of the owner/director. Reviewed manually before verificationStatus flips to "verified".
   */
  verificationDocs?:
    | {
        label: string;
        file: number | VerificationDocument;
        id?: string | null;
      }[]
    | null;
  /**
   * Controls listing caps in the Listings beforeValidate hook and which dashboard analytics widgets render.
   */
  subscriptionTier?: ('free' | 'pro' | 'premium') | null;
  subscriptionRenewsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-documents".
 */
export interface VerificationDocument {
  id: number;
  ownerType: 'user' | 'dealer' | 'service-provider';
  ownerId: string;
  documentType: 'national-id' | 'business-permit' | 'kra-pin' | 'professional-certificate' | 'other';
  status?: ('pending' | 'accepted' | 'rejected' | 'expired') | null;
  expiresAt?: string | null;
  reviewNote?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crsp-schedule".
 */
export interface CrspSchedule {
  id: number;
  /**
   * Make/manufacturer exactly as supplied by the KRA CRSP source.
   */
  make: string;
  /**
   * Vehicle, motorcycle, tractor or grader model exactly as supplied by the KRA CRSP source.
   */
  model: string;
  /**
   * KRA model number where supplied by the source schedule.
   */
  modelNumber?: string | null;
  /**
   * Transmission exactly as supplied by the KRA source, for example AT, 6MT or CVT.
   */
  transmission?: string | null;
  /**
   * Drive configuration where supplied, for example 2WD, 4WD, AWD, FWD or RWD.
   */
  driveConfiguration?: string | null;
  /**
   * Original KRA engine-capacity value preserved as text. This supports values such as 3000, 399 and 63 kWh.
   */
  engineCapacityText?: string | null;
  /**
   * Numeric engine capacity in cc, populated only when the KRA source value is a numeric cc value.
   */
  engineCc?: number | null;
  /**
   * Body type where supplied by the KRA motor-vehicle schedule, for example SUV or HATCHBACK.
   */
  bodyType?: string | null;
  /**
   * Gross vehicle weight in kilograms where supplied by the KRA source.
   */
  gvwKg?: number | null;
  /**
   * Seating capacity where supplied by the KRA source.
   */
  seatingCapacity?: number | null;
  /**
   * Fuel value exactly as supplied by the KRA source, such as GASOLINE, DIESEL, HYBRID or ELECTRIC.
   */
  fuelType?: string | null;
  /**
   * The actual CRSP source-sheet family. These values correspond to the three vehicle-data sheets in the July 2025 KRA workbook.
   */
  sourceGroup: 'motor-vehicle' | 'motorcycle' | 'tractor-grader';
  /**
   * Current Retail Selling Price (CRSP) in Kenyan shillings, as supplied by the KRA source.
   */
  crspValueKes: number;
  /**
   * True when this row has been imported from or directly verified against the official KRA CRSP source.
   */
  verified?: boolean | null;
  /**
   * Source/provenance note, including the KRA workbook and source sheet used for this record.
   */
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-providers".
 */
export interface ServiceProvider {
  id: number;
  owner: number | User;
  businessName: string;
  slug: string;
  logo?: (number | null) | Media;
  description: string;
  services: (
    | 'certified-mechanic'
    | 'auto-electrical'
    | 'body-painting'
    | 'tinting'
    | 'detailing'
    | 'identity-marking'
    | 'inspection'
    | 'spare-parts'
    | 'car-hire'
    | 'leasing'
    | 'towing'
  )[];
  /**
   * Comma-separated makes/models.
   */
  makesServiced?: string | null;
  website?: string | null;
  contactPhone: string;
  whatsappNumber?: string | null;
  county: string;
  town?: string | null;
  physicalAddress?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  verificationStatus?: ('unverified' | 'pending' | 'verified' | 'rejected' | 'expired') | null;
  verificationExpiresAt?: string | null;
  verificationNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  body: string;
  coverImage?: (number | null) | Media;
  authorName: string;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    indexing?: ('auto' | 'index' | 'noindex') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  body: string;
  coverImage?: (number | null) | Media;
  authorName: string;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    indexing?: ('auto' | 'index' | 'noindex') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  author: number | User;
  targetType: 'dealer' | 'service-provider' | 'seller';
  targetId: string;
  rating: number;
  title: string;
  body: string;
  status?: ('pending' | 'published' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  reporter?: (number | null) | User;
  targetType: 'listing' | 'user' | 'dealer' | 'service-provider';
  targetId: string;
  reason: 'suspected-fraud' | 'advance-fee-scam' | 'misleading-listing' | 'impersonation' | 'abuse' | 'other';
  details?: string | null;
  status?: ('open' | 'triaged' | 'under-review' | 'actioned' | 'resolved' | 'dismissed') | null;
  assignedTo?: (number | null) | User;
  moderatorNote?: string | null;
  resolution?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  sender?: (number | null) | User;
  name: string;
  email?: string | null;
  phone?: string | null;
  subject: string;
  message: string;
  status?: ('new' | 'in-progress' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-searches".
 */
export interface SavedSearch {
  id: number;
  user: number | User;
  name: string;
  /**
   * Normalised URL query, without the leading question mark.
   */
  queryString: string;
  /**
   * Structured copy of the saved search filters.
   */
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  frequency: 'instant' | 'daily' | 'weekly' | 'off';
  channels?: ('in-app' | 'email' | 'sms' | 'whatsapp')[] | null;
  active?: boolean | null;
  /**
   * Updated by the alerts worker.
   */
  lastNotifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  type: 'new-listing' | 'price-drop' | 'new-verified-business' | 'wanted-response' | 'system';
  title: string;
  body: string;
  href?: string | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | User;
  action: string;
  targetType: string;
  targetId: string;
  previous?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  next?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  note?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  participants: (number | User)[];
  listing?: (number | null) | Listing;
  lastMessageAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  conversation: number | Conversation;
  sender: number | User;
  body: string;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-submissions".
 */
export interface WhatsappSubmission {
  id: number;
  fromPhone: string;
  rawText?: string | null;
  parsed?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  claimedBy?: (number | null) | User;
  claimTokenUsedAt?: string | null;
  claimExpiresAt?: string | null;
  status?: ('received' | 'needs-details' | 'claimed' | 'under-review' | 'approved' | 'rejected' | 'converted') | null;
  onboardingStatus?: ('unassigned' | 'assigned' | 'awaiting-dealer' | 'dealer-approved' | 'completed') | null;
  assignedTo?: (number | null) | User;
  followUpAt?: string | null;
  slaDueAt?: string | null;
  staffNotes?: string | null;
  dealer?: (number | null) | Dealer;
  listing?: (number | null) | Listing;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-messages".
 */
export interface WhatsappMessage {
  id: number;
  direction: 'inbound' | 'outbound';
  toPhone?: string | null;
  fromPhone?: string | null;
  body?: string | null;
  submission?: (number | null) | WhatsappSubmission;
  providerMessageId?: string | null;
  status?: ('queued' | 'sent' | 'delivered' | 'read' | 'failed') | null;
  attempts?: number | null;
  lastError?: string | null;
  sentAt?: string | null;
  deliveredAt?: string | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-media".
 */
export interface WhatsappMedia {
  id: number;
  submission: number | WhatsappSubmission;
  providerMediaId: string;
  reviewStatus?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-orders".
 */
export interface FeaturedOrder {
  id: number;
  listing: number | Listing;
  user: number | User;
  plan: 'boost-3d' | 'boost-7d' | 'boost-30d' | 'homepage-spotlight-7d';
  /**
   * KES, snapshotted from PLANS at order time so later price changes never rewrite history.
   */
  amount: number;
  durationDays: number;
  paymentProvider?: ('mpesa' | 'card') | null;
  /**
   * Daraja CheckoutRequestID, used to match the async callback back to this order.
   */
  providerCheckoutId?: string | null;
  status?: ('pending' | 'paid' | 'failed' | 'expired') | null;
  startDate?: string | null;
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  listing: number | Listing;
  /**
   * Set if the enquirer was logged in; null for anonymous browse-and-WhatsApp visitors.
   */
  buyerUser?: (number | null) | User;
  buyerName?: string | null;
  buyerPhone?: string | null;
  buyerEmail?: string | null;
  message?: string | null;
  channel: 'whatsapp' | 'phone' | 'form';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inspections".
 */
export interface Inspection {
  id: number;
  listing: number | Listing;
  requestedBy?: (number | null) | User;
  status?: ('requested' | 'scheduled' | 'completed' | 'failed') | null;
  /**
   * Staff account that performed the check.
   */
  inspector?: (number | null) | User;
  inspectionDate?: string | null;
  /**
   * e.g. Engine, Transmission, Brakes, Suspension, Electricals, Body/frame, Logbook match, Chassis/VIN match.
   */
  checklist?:
    | {
        item: string;
        result?: ('pass' | 'fail' | 'not-applicable') | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  overallResult?: ('pass' | 'pass-with-notes' | 'fail') | null;
  /**
   * PDF report, shown to buyers as "View inspection report" on the listing.
   */
  reportFile?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-otps".
 */
export interface PhoneOtp {
  id: number;
  phone: string;
  codeHash: string;
  expiresAt: string;
  attempts?: number | null;
  consumed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'dealers';
        value: number | Dealer;
      } | null)
    | ({
        relationTo: 'service-providers';
        value: number | ServiceProvider;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'saved-searches';
        value: number | SavedSearch;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'verification-documents';
        value: number | VerificationDocument;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'whatsapp-submissions';
        value: number | WhatsappSubmission;
      } | null)
    | ({
        relationTo: 'whatsapp-messages';
        value: number | WhatsappMessage;
      } | null)
    | ({
        relationTo: 'whatsapp-media';
        value: number | WhatsappMedia;
      } | null)
    | ({
        relationTo: 'featured-orders';
        value: number | FeaturedOrder;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inspections';
        value: number | Inspection;
      } | null)
    | ({
        relationTo: 'phone-otps';
        value: number | PhoneOtp;
      } | null)
    | ({
        relationTo: 'crsp-schedule';
        value: number | CrspSchedule;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  publicSlug?: T;
  bio?: T;
  website?: T;
  county?: T;
  town?: T;
  accountStatus?: T;
  suspensionEndsAt?: T;
  moderationNote?: T;
  verificationExpiresAt?: T;
  phone?: T;
  whatsappOptIn?: T;
  role?: T;
  requestedRole?: T;
  avatar?: T;
  idVerified?: T;
  savedListings?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  owner?: T;
  businessName?: T;
  slug?: T;
  logo?: T;
  coverImage?: T;
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        indexing?: T;
      };
  county?: T;
  town?: T;
  physicalAddress?: T;
  latitude?: T;
  longitude?: T;
  verificationExpiresAt?: T;
  verificationNote?: T;
  contactPhone?: T;
  whatsappNumber?: T;
  dealsIn?: T;
  verificationStatus?: T;
  verificationDocs?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  subscriptionTier?: T;
  subscriptionRenewsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-providers_select".
 */
export interface ServiceProvidersSelect<T extends boolean = true> {
  owner?: T;
  businessName?: T;
  slug?: T;
  logo?: T;
  description?: T;
  services?: T;
  makesServiced?: T;
  website?: T;
  contactPhone?: T;
  whatsappNumber?: T;
  county?: T;
  town?: T;
  physicalAddress?: T;
  latitude?: T;
  longitude?: T;
  verificationStatus?: T;
  verificationExpiresAt?: T;
  verificationNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seller?: T;
  dealer?: T;
  category?: T;
  condition?: T;
  make?: T;
  model?: T;
  makeSlug?: T;
  modelSlug?: T;
  modelNumber?: T;
  trim?: T;
  yearOfManufacture?: T;
  transmission?: T;
  driveConfiguration?: T;
  fuelType?: T;
  engineCc?: T;
  mileageKm?: T;
  bodyType?: T;
  grossVehicleWeightKg?: T;
  seatingCapacity?: T;
  color?: T;
  crspRecord?: T;
  crspValueKes?: T;
  heavyMachineSpecs?:
    | T
    | {
        equipmentType?: T;
        powerRatingHp?: T;
        operatingHours?: T;
        capacityOrTonnage?: T;
        attachments?: T;
      };
  sparePartDetails?:
    | T
    | {
        partType?: T;
        compatibleModels?: T;
        partCondition?: T;
      };
  dutyStatus?: T;
  vinOrChassis?: T;
  price?: T;
  negotiable?: T;
  currency?: T;
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        indexing?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  videoUrl?: T;
  county?: T;
  town?: T;
  latitude?: T;
  longitude?: T;
  status?: T;
  moderationFlag?: T;
  riskScore?: T;
  riskReasons?:
    | T
    | {
        reason?: T;
        id?: T;
      };
  moderationNote?: T;
  featured?: T;
  featuredUntil?: T;
  views?: T;
  inquiryCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  authorName?: T;
  publishedAt?: T;
  status?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        indexing?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  authorName?: T;
  publishedAt?: T;
  status?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        indexing?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  targetType?: T;
  targetId?: T;
  rating?: T;
  title?: T;
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reporter?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  details?: T;
  status?: T;
  assignedTo?: T;
  moderatorNote?: T;
  resolution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  sender?: T;
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-searches_select".
 */
export interface SavedSearchesSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  queryString?: T;
  filters?: T;
  frequency?: T;
  channels?: T;
  active?: T;
  lastNotifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  body?: T;
  href?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  previous?: T;
  next?: T;
  note?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-documents_select".
 */
export interface VerificationDocumentsSelect<T extends boolean = true> {
  ownerType?: T;
  ownerId?: T;
  documentType?: T;
  status?: T;
  expiresAt?: T;
  reviewNote?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  participants?: T;
  listing?: T;
  lastMessageAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  sender?: T;
  body?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-submissions_select".
 */
export interface WhatsappSubmissionsSelect<T extends boolean = true> {
  fromPhone?: T;
  rawText?: T;
  parsed?: T;
  claimedBy?: T;
  claimTokenUsedAt?: T;
  claimExpiresAt?: T;
  status?: T;
  onboardingStatus?: T;
  assignedTo?: T;
  followUpAt?: T;
  slaDueAt?: T;
  staffNotes?: T;
  dealer?: T;
  listing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-messages_select".
 */
export interface WhatsappMessagesSelect<T extends boolean = true> {
  direction?: T;
  toPhone?: T;
  fromPhone?: T;
  body?: T;
  submission?: T;
  providerMessageId?: T;
  status?: T;
  attempts?: T;
  lastError?: T;
  sentAt?: T;
  deliveredAt?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-media_select".
 */
export interface WhatsappMediaSelect<T extends boolean = true> {
  submission?: T;
  providerMediaId?: T;
  reviewStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-orders_select".
 */
export interface FeaturedOrdersSelect<T extends boolean = true> {
  listing?: T;
  user?: T;
  plan?: T;
  amount?: T;
  durationDays?: T;
  paymentProvider?: T;
  providerCheckoutId?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  listing?: T;
  buyerUser?: T;
  buyerName?: T;
  buyerPhone?: T;
  buyerEmail?: T;
  message?: T;
  channel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inspections_select".
 */
export interface InspectionsSelect<T extends boolean = true> {
  listing?: T;
  requestedBy?: T;
  status?: T;
  inspector?: T;
  inspectionDate?: T;
  checklist?:
    | T
    | {
        item?: T;
        result?: T;
        note?: T;
        id?: T;
      };
  overallResult?: T;
  reportFile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-otps_select".
 */
export interface PhoneOtpsSelect<T extends boolean = true> {
  phone?: T;
  codeHash?: T;
  expiresAt?: T;
  attempts?: T;
  consumed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crsp-schedule_select".
 */
export interface CrspScheduleSelect<T extends boolean = true> {
  make?: T;
  model?: T;
  modelNumber?: T;
  transmission?: T;
  driveConfiguration?: T;
  engineCapacityText?: T;
  engineCc?: T;
  bodyType?: T;
  gvwKg?: T;
  seatingCapacity?: T;
  fuelType?: T;
  sourceGroup?: T;
  crspValueKes?: T;
  verified?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}